/**
 * Autogenerated by Thrift Compiler (0.14.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.ycu.tang.msbplatform.speed.thrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.14.2)", date = "2021-11-03")
public class OrigSystem extends org.apache.thrift.TUnion<OrigSystem, OrigSystem._Fields> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("OrigSystem");
  private static final org.apache.thrift.protocol.TField PAGE_VIEW_FIELD_DESC = new org.apache.thrift.protocol.TField("page_view", org.apache.thrift.protocol.TType.STRUCT, (short)1);
  private static final org.apache.thrift.protocol.TField EXTERNAL_DATA_FIELD_DESC = new org.apache.thrift.protocol.TField("external_data", org.apache.thrift.protocol.TType.STRUCT, (short)2);

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    PAGE_VIEW((short)1, "page_view"),
    EXTERNAL_DATA((short)2, "external_data");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // PAGE_VIEW
          return PAGE_VIEW;
        case 2: // EXTERNAL_DATA
          return EXTERNAL_DATA;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.PAGE_VIEW, new org.apache.thrift.meta_data.FieldMetaData("page_view", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, PageViewSystem.class)));
    tmpMap.put(_Fields.EXTERNAL_DATA, new org.apache.thrift.meta_data.FieldMetaData("external_data", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, ExternalDataSystem.class)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(OrigSystem.class, metaDataMap);
  }

  public OrigSystem() {
    super();
  }

  public OrigSystem(_Fields setField, java.lang.Object value) {
    super(setField, value);
  }

  public OrigSystem(OrigSystem other) {
    super(other);
  }
  public OrigSystem deepCopy() {
    return new OrigSystem(this);
  }

  public static OrigSystem page_view(PageViewSystem value) {
    OrigSystem x = new OrigSystem();
    x.setPage_view(value);
    return x;
  }

  public static OrigSystem external_data(ExternalDataSystem value) {
    OrigSystem x = new OrigSystem();
    x.setExternal_data(value);
    return x;
  }


  @Override
  protected void checkType(_Fields setField, java.lang.Object value) throws java.lang.ClassCastException {
    switch (setField) {
      case PAGE_VIEW:
        if (value instanceof PageViewSystem) {
          break;
        }
        throw new java.lang.ClassCastException("Was expecting value of type PageViewSystem for field 'page_view', but got " + value.getClass().getSimpleName());
      case EXTERNAL_DATA:
        if (value instanceof ExternalDataSystem) {
          break;
        }
        throw new java.lang.ClassCastException("Was expecting value of type ExternalDataSystem for field 'external_data', but got " + value.getClass().getSimpleName());
      default:
        throw new java.lang.IllegalArgumentException("Unknown field id " + setField);
    }
  }

  @Override
  protected java.lang.Object standardSchemeReadValue(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TField field) throws org.apache.thrift.TException {
    _Fields setField = _Fields.findByThriftId(field.id);
    if (setField != null) {
      switch (setField) {
        case PAGE_VIEW:
          if (field.type == PAGE_VIEW_FIELD_DESC.type) {
            PageViewSystem page_view;
            page_view = new PageViewSystem();
            page_view.read(iprot);
            return page_view;
          } else {
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            return null;
          }
        case EXTERNAL_DATA:
          if (field.type == EXTERNAL_DATA_FIELD_DESC.type) {
            ExternalDataSystem external_data;
            external_data = new ExternalDataSystem();
            external_data.read(iprot);
            return external_data;
          } else {
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            return null;
          }
        default:
          throw new java.lang.IllegalStateException("setField wasn't null, but didn't match any of the case statements!");
      }
    } else {
      org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
      return null;
    }
  }

  @Override
  protected void standardSchemeWriteValue(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    switch (setField_) {
      case PAGE_VIEW:
        PageViewSystem page_view = (PageViewSystem)value_;
        page_view.write(oprot);
        return;
      case EXTERNAL_DATA:
        ExternalDataSystem external_data = (ExternalDataSystem)value_;
        external_data.write(oprot);
        return;
      default:
        throw new java.lang.IllegalStateException("Cannot write union with unknown field " + setField_);
    }
  }

  @Override
  protected java.lang.Object tupleSchemeReadValue(org.apache.thrift.protocol.TProtocol iprot, short fieldID) throws org.apache.thrift.TException {
    _Fields setField = _Fields.findByThriftId(fieldID);
    if (setField != null) {
      switch (setField) {
        case PAGE_VIEW:
          PageViewSystem page_view;
          page_view = new PageViewSystem();
          page_view.read(iprot);
          return page_view;
        case EXTERNAL_DATA:
          ExternalDataSystem external_data;
          external_data = new ExternalDataSystem();
          external_data.read(iprot);
          return external_data;
        default:
          throw new java.lang.IllegalStateException("setField wasn't null, but didn't match any of the case statements!");
      }
    } else {
      throw new org.apache.thrift.protocol.TProtocolException("Couldn't find a field with field id " + fieldID);
    }
  }

  @Override
  protected void tupleSchemeWriteValue(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    switch (setField_) {
      case PAGE_VIEW:
        PageViewSystem page_view = (PageViewSystem)value_;
        page_view.write(oprot);
        return;
      case EXTERNAL_DATA:
        ExternalDataSystem external_data = (ExternalDataSystem)value_;
        external_data.write(oprot);
        return;
      default:
        throw new java.lang.IllegalStateException("Cannot write union with unknown field " + setField_);
    }
  }

  @Override
  protected org.apache.thrift.protocol.TField getFieldDesc(_Fields setField) {
    switch (setField) {
      case PAGE_VIEW:
        return PAGE_VIEW_FIELD_DESC;
      case EXTERNAL_DATA:
        return EXTERNAL_DATA_FIELD_DESC;
      default:
        throw new java.lang.IllegalArgumentException("Unknown field id " + setField);
    }
  }

  @Override
  protected org.apache.thrift.protocol.TStruct getStructDesc() {
    return STRUCT_DESC;
  }

  @Override
  protected _Fields enumForId(short id) {
    return _Fields.findByThriftIdOrThrow(id);
  }

  @org.apache.thrift.annotation.Nullable
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }


  public PageViewSystem getPage_view() {
    if (getSetField() == _Fields.PAGE_VIEW) {
      return (PageViewSystem)getFieldValue();
    } else {
      throw new java.lang.RuntimeException("Cannot get field 'page_view' because union is currently set to " + getFieldDesc(getSetField()).name);
    }
  }

  public void setPage_view(PageViewSystem value) {
    setField_ = _Fields.PAGE_VIEW;
    value_ = java.util.Objects.requireNonNull(value,"_Fields.PAGE_VIEW");
  }

  public ExternalDataSystem getExternal_data() {
    if (getSetField() == _Fields.EXTERNAL_DATA) {
      return (ExternalDataSystem)getFieldValue();
    } else {
      throw new java.lang.RuntimeException("Cannot get field 'external_data' because union is currently set to " + getFieldDesc(getSetField()).name);
    }
  }

  public void setExternal_data(ExternalDataSystem value) {
    setField_ = _Fields.EXTERNAL_DATA;
    value_ = java.util.Objects.requireNonNull(value,"_Fields.EXTERNAL_DATA");
  }

  public boolean isSetPage_view() {
    return setField_ == _Fields.PAGE_VIEW;
  }


  public boolean isSetExternal_data() {
    return setField_ == _Fields.EXTERNAL_DATA;
  }


  public boolean equals(java.lang.Object other) {
    if (other instanceof OrigSystem) {
      return equals((OrigSystem)other);
    } else {
      return false;
    }
  }

  public boolean equals(OrigSystem other) {
    return other != null && getSetField() == other.getSetField() && getFieldValue().equals(other.getFieldValue());
  }

  @Override
  public int compareTo(OrigSystem other) {
    int lastComparison = org.apache.thrift.TBaseHelper.compareTo(getSetField(), other.getSetField());
    if (lastComparison == 0) {
      return org.apache.thrift.TBaseHelper.compareTo(getFieldValue(), other.getFieldValue());
    }
    return lastComparison;
  }


  @Override
  public int hashCode() {
    java.util.List<java.lang.Object> list = new java.util.ArrayList<java.lang.Object>();
    list.add(this.getClass().getName());
    org.apache.thrift.TFieldIdEnum setField = getSetField();
    if (setField != null) {
      list.add(setField.getThriftFieldId());
      java.lang.Object value = getFieldValue();
      if (value instanceof org.apache.thrift.TEnum) {
        list.add(((org.apache.thrift.TEnum)getFieldValue()).getValue());
      } else {
        list.add(value);
      }
    }
    return list.hashCode();
  }
  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }


  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }


}
